### ISSUE TITLE
Ripple restore --force occasionally 

### ISSUE THREAD

**Issue by Scooletz** [FubuMvcArchive/ripple#117]
The error cannot be reproduced. It happens occasionally. The exception stack trace is like that:

ripple: Error executing ExplodeDownloadedNugets
System.UnauthorizedAccessException: Access to the path 'C:\projects\ProjectA\packages\ProjectB.ExternalContract\lib\net40\' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.InternalGetFiles(String path, String searchPattern, SearchOption searchOption)
   at FubuCore.FileSet.<>c__DisplayClass3.<getAllDistinctFiles>b__2(String x)
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__81`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FubuCore.FileSystem.FindFiles(String directory, FileSet searchSpecification)
   at ripple.Nuget.NugetStorage.Dependencies(Solution solution)
   at ripple.Model.Solution.LocalDependencies()
   at ripple.Model.Solution.Describe(Description description)
   at FubuCore.Descriptions.Description.For(Object target)
   at FubuCore.Descriptions.DescriptionExtensions.ToDescriptionText(Object target)
   at ripple.RippleLog.FileListener.DebugMessage(Object message)
   at FubuCore.Logging.ListenerCollection.<>c__DisplayClass6`1.<>c__DisplayClass8.<findAction>b__2(ILogListener x)

**Comment by jeremydmiller** [comment]
I'm not sure we're ever going to be able to completely make the file locking problems go away.  We can try some "retry" mechanics in there I guess.

**Comment by Scooletz** [comment]
Is it Nuget.Core or VS? What do you think? I'd love to solve this but as I cannot distil it in a test, I don't know what needs fixing.
I thought about passing all exploded nugets with some procedure removing attributes but I cannot tell what causes the problem.

**Comment by jmarnold** [comment]
This one has been baffling me for a while. When we clean out a directory (e.g., src/packages/MyPackage), we call the "ForceClean" extension method which does do a retry:

https://github.com/DarthFubuMVC/ripple/blob/master/src/ripple/FileSystemExtensions.cs#L10

It still gets caught in a weird loop from time to time and completely screws up a directory.

**Comment by Scooletz** [comment]
The standard NuGet client skips this problem by storing all in the package-version problem, so there's nothing to be taken from it as ripple uses the directory-per-package strategy. Managing file system from .NET? Is it the thing I should search for?
