### ISSUE TITLE
describe-graph command is broken

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#138]
Might just be able to handle bad data.

Trying to do describe-graph with fubucore gives:

Trying to read a Ripple SolutionGraph from C:\code
Classic Mode Detected
Classic Mode Detected
ERROR: System.ArgumentException: The key 'fubumvc' already exists. ---> System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at FubuCore.DictionaryExtensions.SmartAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, TValue value) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\DictionaryExtensions.cs:line 28
   --- End of inner exception stack trace ---
   at FubuCore.DictionaryExtensions.SmartAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, TValue value) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\DictionaryExtensions.cs:line 32
   at FubuCore.DependencyAnalysis.DependencyGraph`1.RegisterItem(T item) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\DependencyAnalysis\DependencyGraph.cs:line 29
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\EnumerableExtensions.cs:line 78
   at ripple.Model.SolutionGraph.<>c__DisplayClasse.<.ctor>b__5() in c:\code\ripple\src\ripple\Model\SolutionGraph.cs:line 31
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at ripple.Model.SolutionGraph.Describe(Description description) in c:\code\ripple\src\ripple\Model\SolutionGraph.cs:line 76
   at FubuCore.Descriptions.Description.For(Object target) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\Descriptions\Description.cs:line 86
   at FubuCore.Descriptions.DescriptionExtensions.ToDescriptionText(Object target) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\Descriptions\DescriptionTextWriter.cs:line 14
   at ripple.Commands.DescribeGraphCommand.Execute(DescribeGraphInput input) in c:\code\ripple\src\ripple\Commands\DescribeGraphCommand.cs:line 16
   at ripple.Program.Main(String[] args) in c:\code\ripple\src\ripple\Program.cs:line 18

**Comment by STRUDSO** [comment]
Had the same issue today. it was because i had 2 ripple.config with the same name in it, (copy/paste error).

Let me know if i should spent a little time coming up with a better exception. As i see it, you cannot have multiple "solutions" with same name in the "ripple" structure.
