### ISSUE TITLE
Running "ripple local" a second time fails

### ISSUE THREAD

**Issue by STRUDSO** [FubuMvcArchive/ripple#153]
Could not find {nugetpackagename}
   at ripple.Nuget.LocalDependencies.Get(String name) in c:\src\fromgit\ripple\src\ripple\Nuget\LocalDependencies.cs:line 42
   at ripple.Model.Solution.NugetFolderFor(String nugetName) in c:\src\fromgit\ripple\src\ripple\Model\Solution.cs:line 494
   at ripple.Model.Solution.NugetFolderFor(NugetSpec spec) in c:\src\fromgit\ripple\src\ripple\Model\Solution.cs:line 489
   at ripple.Local.MoveNugetAssemblies.Execute(IRippleStepRunner runner) in c:\src\fromgit\ripple\src\ripple\Local\MoveNugetAssemblies.cs:line 69
   at ripple.Local.RippleRunner.<>c__DisplayClass5.<runStep>b__4() in c:\src\fromgit\ripple\src\ripple\Local\RippleRunner.cs:line 63
   at ripple.Local.RippleLogger.Indent(Action action) in c:\src\fromgit\ripple\src\ripple\Local\RippleLogger.cs:line 18
   at ripple.Local.RippleRunner.runStep(IRippleStep step, Int32 number, Int32 total) in c:\src\fromgit\ripple\src\ripple\Local\RippleRunner.cs:line 46
   at ripple.Local.RippleRunner.<>c__DisplayClass2.<RunPlan>b__0(IRippleStep step) in c:\src\fromgit\ripple\src\ripple\Local\RippleRunner.cs:line 27
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\EnumerableExtensions.cs:line 76
   at ripple.Local.RippleRunner.RunPlan(SolutionGraph graph, RipplePlanRequirements requirements) in c:\src\fromgit\ripple\src\ripple\Local\RippleRunner.cs:line 27
   at ripple.Commands.LocalCommand.Execute(LocalInput input) in c:\src\fromgit\ripple\src\ripple\Commands\LocalCommand.cs:line 61
   at FubuCore.CommandLine.FubuCommand`1.Execute(Object input) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\CommandLine\FubuCommand.cs:line 41
   at FubuCore.CommandLine.CommandRun.Execute() in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\CommandLine\CommandRun.cs:line 10
   at FubuCore.CommandLine.CommandExecutor.Execute(String[] args) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\CommandLine\CommandExecutor.cs:line 60
   at ripple.Program.Main(String[] args) in c:\src\fromgit\ripple\src\ripple\Program.cs:line 18

Seems like it's clearing out the package folder in destination and then deleting the .nupkg, but relying on finding a {nugetpackagename}.nupkg on second invocation of "ripple local".

Maybe i've totally missed the point of ripple, but seem like a core use case to me, to be able to run ripple local multiple times?

**Comment by STRUDSO** [comment]
I tried to clean only "subdirs", but don't know how often stuff is put into the "root" folder of a nuget package:
https://github.com/STRUDSO/ripple/commit/4bbc73079f8d4b87c466f55b5b9562e018988b42

I can see that you have logged issues to delete the local command and replace with something else?
