### ISSUE TITLE
SingleOrDefault failure from NugetFeed.find(Dependency)

### ISSUE THREAD

**Issue by SimonCropp** [FubuMvcArchive/ripple#193]
runing https://github.com/DarthFubuMVC/ripple/commit/a848982635f80e18d63eb534c4822f6a32a648e4 i get this exception 

```
  String: Problem with restore Sequence contains more than one element System.InvalidOperationException: Sequence contains more than one element
     at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
     at ripple.Nuget.NugetFeed.find(Dependency query) in c:\Code\ripple\src\ripple\Nuget\NugetFeed.cs:line 72
     at ripple.Nuget.NugetFeedBase.Find(Dependency query) in c:\Code\ripple\src\ripple\Nuget\NugetFeedBase.cs:line 23
     at ripple.Nuget.NugetSearch.<>c__DisplayClasse.<FindNuget>b__d(INugetFeed feed) in c:\Code\ripple\src\ripple\Nuget\NugetSearch.cs:line 139
     at ripple.Nuget.NugetSearch.FindNuget(IEnumerable`1 feeds, Func`2 find) in c:\Code\ripple\src\ripple\Nuget\NugetSearch.cs:line 129
     at ripple.Nuget.NugetSearch.FindNuget(Solution solution, Dependency dependency) in c:\Code\ripple\src\ripple\Nuget\NugetSearch.cs:line 139
     at ripple.Nuget.DefaultFinder.Find(Solution solution, Dependency dependency) in c:\Code\ripple\src\ripple\Nuget\DefaultFinder.cs:line 14
     at ripple.Nuget.NugetSearch.<>c__DisplayClass8.<fill>b__7(Task`1 task) in c:\Code\ripple\src\ripple\Nuget\NugetSearch.cs:line 89
     at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
```

**Comment by SimonCropp** [comment]
problem is here https://github.com/DarthFubuMVC/ripple/blob/master/src/ripple/Nuget/NugetFeed.cs#L72

as suggested by @jmarnold this seems to work

```
        var package = _repository
            .FindPackages(query.Name, versionSpec, query.DetermineStability(_stability) == NugetStability.Anything, true)
            .OrderByDescending(x => x.Version)
            .FirstOrDefault();
```
