### ISSUE TITLE
handle corrupted packages

### ISSUE THREAD

**Issue by SimonCropp** [FubuMvcArchive/ripple#197]
corrupted packages should be re downloaded

```
20 Sep 2013 14:37:06: [Error] System.IO.FileFormatException: Archive file cannot be size 0.
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at NuGet.ZipPackage.EnsureManifest()
   at ripple.Nuget.NugetFile.ExplodeTo(String directory)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at ripple.RippleOperation.Execute(Boolean throwOnFailure)
```

**Comment by johnsimons** [comment]
Here is another example:

```
26/09/2013 3:13:55 PM: [Info] Exploding to c:\Projects\ServiceBus.Management\src\packages\NServiceBus
26/09/2013 3:13:55 PM: [Error] Error executing ExplodeDownloadedNugets
26/09/2013 3:13:55 PM: [Error] System.IO.FileFormatException: File contains corrupted data.
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOBlockManager.LoadEndOfCentralDirectoryBlock()
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at NuGet.ZipPackage.EnsureManifest()
   at ripple.Nuget.NugetFile.ExplodeTo(String directory) in c:\Code\ripple\src\ripple\Nuget\NugetFile.cs:line 87
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at ripple.RippleOperation.Execute(Boolean throwOnFailure) in c:\Code\ripple\src\ripple\RippleOperation.cs:line 77
```
