### ISSUE TITLE
Ripple restore fails 

### ISSUE THREAD

**Issue by KevM** [FubuMvcArchive/ripple#218]
This error just started to pop up in our CI

```
...
10/7/2013 2:22:00 PM: [Debug] Searching for structuremap,2.6.3.0,Fixed in C:\Users\ci\AppData\Roaming\ripple
10/7/2013 2:22:00 PM: [Debug] Downloading From filesystem: C:\Users\ci\AppData\Roaming\ripple\structuremap.2.6.3.0.nupkg
10/7/2013 2:22:00 PM: [Debug] Searching for structuremap.automocking,2.6.3.0,Fixed in C:\Users\ci\AppData\Roaming\ripple
10/7/2013 2:22:00 PM: [Debug] Downloading From filesystem: C:\Users\ci\AppData\Roaming\ripple\structuremap.automocking.2.6.3.0.nupkg
10/7/2013 2:22:00 PM: [Debug] Searching for UnionArgParser,0.5.3 in C:\Users\ci\AppData\Roaming\ripple
10/7/2013 2:22:00 PM: [Debug] Searching for latest of UnionArgParser in C:\TeamCity\buildAgent\work\ed856b5e5c98a3b1\nugets
10/7/2013 2:22:01 PM: [Debug] Downloading From filesystem: C:\Users\ci\AppData\Roaming\ripple\UnionArgParser.0.5.3.0.nupkg
10/7/2013 2:22:01 PM: [Debug] Downloading From filesystem: C:\Users\ci\AppData\Roaming\ripple\Selenium.Support.2.35.0.0.nupkg
10/7/2013 2:22:01 PM: [Error] Error executing DownloadMissingNugets
10/7/2013 2:22:01 PM: [Error] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The context is not currently tracking the entity.
   at System.Data.Services.Client.DataServiceContext.EnsureContained(Object resource, String parameterName)
   at System.Data.Services.Client.DataServiceContext.GetReadStreamUri(Object entity)
   at NuGet.DataServiceContextWrapper.GetReadStreamUri(Object entity)
   at NuGet.DataServicePackage.EnsurePackage(IPackageCacheRepository cacheRepository)
   at NuGet.DataServicePackage.GetStream()
   at ripple.Nuget.RemotePackageDownloader.DownloadTo(SolutionMode mode, String filename)
   at ripple.Nuget.RemoteNuget.DownloadTo(Solution solution, String directory)
   at ripple.Nuget.CacheableNuget.DownloadTo(Solution solution, String directory)
   at ripple.Steps.DownloadMissingNugets.<>c__DisplayClass5.<restore>b__4(Task`1 task)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ripple.Steps.DownloadMissingNugets.Execute(RippleInput input, IRippleStepRunner runner)
   at ripple.RippleOperation.Execute(Boolean throwOnFailure)
---> (Inner Exception #0) System.InvalidOperationException: The context is not currently tracking the entity.
   at System.Data.Services.Client.DataServiceContext.EnsureContained(Object resource, String parameterName)
   at System.Data.Services.Client.DataServiceContext.GetReadStreamUri(Object entity)
   at NuGet.DataServiceContextWrapper.GetReadStreamUri(Object entity)
   at NuGet.DataServicePackage.EnsurePackage(IPackageCacheRepository cacheRepository)
   at NuGet.DataServicePackage.GetStream()
   at ripple.Nuget.RemotePackageDownloader.DownloadTo(SolutionMode mode, String filename)
   at ripple.Nuget.RemoteNuget.DownloadTo(Solution solution, String directory)
   at ripple.Nuget.CacheableNuget.DownloadTo(Solution solution, String directory)
   at ripple.Steps.DownloadMissingNugets.<>c__DisplayClass5.<restore>b__4(Task`1 task)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

I downgraded ripple-cli gem a version at a time and continued to see this until I got to **ripple 2.0**. 

Josh mentioned that this might be related to resource handling between the odata (Nuget) server and client and we have a local Nuget server in play so I restarted our local Nuget server and the problem went away. 

Also: ripple restore in 2.3 is crazy fast. :love_letter:

**Comment by jeremydmiller** [comment]
Look hard at the stack trace and where it's coming from at the top.  When we've done the google hunt, it comes down to a known error against the Nuget server itself.

The long term solution that Josh & I have discussed is to do more decoupling from us to the Nuget.Core library so that we don't hit the oData errors like this.

**Comment by KevM** [comment]
I get that. Not dinging Ripple on that one. I wanted to create the issue to get the work around out there for others to know about.
