### ISSUE TITLE
Cannot install System.Management.Automation without --version using ripple

### ISSUE THREAD

**Issue by agross** [FubuMvcArchive/ripple#240]
```
>ripple install System.Management.Automation.dll
Install System.Management.Automation.dll to Solution xyz
* Analyzing System.Management.Automation.dll
ripple: Could not find System.Management.Automation.dll
ripple: Error executing NugetOperation
```

whereas:

```
>NuGet.exe install System.Management.Automation
Installing 'System.Management.Automation 6.1.7601.17515'.
Successfully installed 'System.Management.Automation 6.1.7601.17515'.
```

My only feed in the `ripple.config` is this:

```
<Feed Url="http://nuget.org/api/v2" Mode="Fixed" Stability="ReleasedOnly" />
```

The logfile:

```
09.11.2013 12:23:01: [Info] Install System.Management.Automation to Solution xyz
09.11.2013 12:23:01: [Info] * Analyzing System.Management.Automation
09.11.2013 12:23:02: [Debug] Retrieving latest from http://nuget.org/api/v2/Packages()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&$skip=0&$take=100
09.11.2013 12:23:03: [Debug] The remote server returned an error: (400) Bad Request.
09.11.2013 12:23:03: [Debug]    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ripple.Nuget.FloatingFeed.loadLatestFeed(Int32 page)
   at ripple.Nuget.FloatingFeed.getLatest()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at ripple.Nuget.FloatingFeed.findLatest(Dependency query)
   at ripple.Nuget.NugetFeedBase.FindLatest(Dependency query)
   at ripple.Nuget.FloatingFinder.<>c__DisplayClass5.<Find>b__0(INugetFeed x)
   at ripple.Nuget.NugetSearch.FindNuget(IEnumerable`1 feeds, Func`2 find)
   at ripple.Nuget.FloatingFinder.Find(Solution solution, Dependency dependency)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
09.11.2013 12:23:03: [Error] Could not find System.Management.Automation
09.11.2013 12:23:03: [Error] ripple.RippleFatalError: Could not find System.Management.Automation
09.11.2013 12:23:03: [Error] Error executing NugetOperation
09.11.2013 12:23:03: [Error] ripple.RippleFatalError: Could not find System.Management.Automation
   at ripple.RippleAssert.Fail(String message, Object[] substitutions)
   at ripple.Nuget.NugetPlanBuilder.buildPlan(NugetPlanRequest request, Dependency parent)
   at ripple.Steps.NugetOperation.<>c__DisplayClass1.<PlanFor>b__0(NugetPlanRequest request)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at ripple.Steps.NugetOperation.Execute(RippleInput input, IRippleStepRunner runner)
   at ripple.RippleOperation.Execute(Boolean throwOnFailure)
```

With the fix for #226 the log looks a bit different:

```
09.11.2013 12:24:26: [Info] Install System.Management.Automation to Solution ManagedUC
09.11.2013 12:24:26: [Info] * Analyzing System.Management.Automation
09.11.2013 12:24:30: [Debug] Retrieving latest from http://nuget.org/api/v2/Packages()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&$skip=0&$top=100
09.11.2013 12:24:31: [Debug] Looking for System.Management.Automation in http://nuget.org/api/v2; Found 
09.11.2013 12:24:31: [Debug] 
========================================================================================
LatestNugets: Nugets found from http://nuget.org/api/v2
========================================================================================
     ** Nugets
        * RemoteNuget     Download jQuery.2.0.3.0.nupkg                                 
        * RemoteNuget     Download Newtonsoft.Json.5.0.8.0.nupkg                        
        * RemoteNuget     Download EntityFramework.6.0.1.0.nupkg                        
        * RemoteNuget     Download jQuery.Validation.1.11.1.0.nupkg                     
        * RemoteNuget     Download Microsoft.Web.Infrastructure.1.0.0.0.nupkg           
        * RemoteNuget     Download jQuery.UI.Combined.1.10.3.0.nupkg                    
        * RemoteNuget     Download Microsoft.AspNet.Razor.3.0.0.0.nupkg                 
        * RemoteNuget     Download Modernizr.2.6.2.0.nupkg                              
        * RemoteNuget     Download Microsoft.AspNet.WebPages.3.0.0.0.nupkg              
        * RemoteNuget     Download Microsoft.Net.Http.2.2.15.0.nupkg                    
        * RemoteNuget     Download knockoutjs.3.0.0.0.nupkg                             
        * RemoteNuget     Download Ninject.3.0.1.10.nupkg                               
        * RemoteNuget     Download elmah.1.2.2.0.nupkg                                  
        * RemoteNuget     Download Microsoft.AspNet.WebApi.Client.5.0.0.0.nupkg         
        * RemoteNuget     Download DotNetOpenAuth.OpenId.Core.4.3.3.13295.nupkg         
        * RemoteNuget     Download Microsoft.AspNet.Mvc.5.0.0.0.nupkg                   
        * RemoteNuget     Download WebGrease.1.5.2.0.nupkg                              
        * RemoteNuget     Download elmah.corelibrary.1.2.2.0.nupkg                      
        * RemoteNuget     Download Microsoft.AspNet.WebApi.Core.5.0.0.0.nupkg           
        * RemoteNuget     Download Microsoft.jQuery.Unobtrusive.Validation.3.0.0.0.nupkg
        * RemoteNuget     Download DotNetOpenAuth.OpenId.RelyingParty.4.3.3.13295.nupkg 
        * RemoteNuget     Download Microsoft.AspNet.WebApi.WebHost.5.0.0.0.nupkg        
        * RemoteNuget     Download Microsoft.AspNet.Web.Optimization.1.1.2.0.nupkg      
        * RemoteNuget     Download DotNetOpenAuth.AspNet.4.3.3.13295.nupkg              
        * RemoteNuget     Download Microsoft.AspNet.WebApi.5.0.0.0.nupkg                
        * RemoteNuget     Download DotNetOpenAuth.Core.4.3.3.13295.nupkg                
        * RemoteNuget     Download Nuget.Core.2.7.1.0.nupkg                             
        * RemoteNuget     Download DotNetOpenAuth.OAuth.Consumer.4.3.3.13295.nupkg      
        * RemoteNuget     Download DotNetOpenAuth.OAuth.Core.4.3.3.13295.nupkg          
        * RemoteNuget     Download log4net.2.0.2.0.nupkg                                
        * RemoteNuget     Download NUnit.2.6.3.0.nupkg                                  
        * RemoteNuget     Download Moq.4.1.1309.1617.nupkg                              
        * RemoteNuget     Download elmah.sqlserver.1.2.0.0.nupkg                        
        * RemoteNuget     Download Microsoft.jQuery.Unobtrusive.Ajax.3.0.0.0.nupkg      
        * RemoteNuget     Download microsoft-web-helpers.2.1.20710.2.nupkg              
        * RemoteNuget     Download NuGet.CommandLine.2.7.1.0.nupkg                      
        * RemoteNuget     Download WindowsAzure.Storage.2.1.0.3.nupkg                   
        * RemoteNuget     Download Microsoft.AspNet.WebPages.Data.3.0.0.0.nupkg         
        * RemoteNuget     Download Microsoft.AspNet.WebPages.WebData.3.0.0.0.nupkg      
        * RemoteNuget     Download jquery.mobile.1.3.2.0.nupkg                          

09.11.2013 12:24:31: [Debug] Looking for System.Management.Automation in http://nuget.org/api/v2; Found 
09.11.2013 12:24:31: [Debug] Could not find exact for System.Management.Automation
09.11.2013 12:24:31: [Error] Could not find System.Management.Automation
09.11.2013 12:24:31: [Error] ripple.RippleFatalError: Could not find System.Management.Automation
09.11.2013 12:24:31: [Error] Error executing NugetOperation
09.11.2013 12:24:31: [Error] ripple.RippleFatalError: Could not find System.Management.Automation
   at ripple.RippleAssert.Fail(String message, Object[] substitutions) in d:\Users\agross\Downloads\ripple\src\ripple\RippleAssert.cs:line 22
   at ripple.Nuget.NugetPlanBuilder.buildPlan(NugetPlanRequest request, Dependency parent) in d:\Users\agross\Downloads\ripple\src\ripple\Nuget\NugetPlanBuilder.cs:line 72
   at ripple.Nuget.NugetPlanBuilder.PlanFor(NugetPlanRequest request) in d:\Users\agross\Downloads\ripple\src\ripple\Nuget\NugetPlanBuilder.cs:line 25
   at ripple.Steps.NugetOperation.<>c__DisplayClass1.<PlanFor>b__0(NugetPlanRequest request) in d:\Users\agross\Downloads\ripple\src\ripple\Steps\NugetOperation.cs:line 36
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\EnumerableExtensions.cs:line 76
   at ripple.Steps.NugetOperation.PlanFor(INugetOperationContext context, Solution solution) in d:\Users\agross\Downloads\ripple\src\ripple\Steps\NugetOperation.cs:line 32
   at ripple.Steps.NugetOperation.Execute(RippleInput input, IRippleStepRunner runner) in d:\Users\agross\Downloads\ripple\src\ripple\Steps\NugetOperation.cs:line 17
   at ripple.RippleOperation.Execute(Boolean throwOnFailure) in d:\Users\agross\Downloads\ripple\src\ripple\RippleOperation.cs:line 77
```

If I specify `--version 6.1.7601.17515` installation works, but `ripple restore` fails:

```
>ripple restore
Restoring dependencies for solution xyz to somewhere\packages
ripple: Error executing DownloadMissingNugets
```

**Comment by jmarnold** [comment]
This looks like it's getting treated as a floating feed and that's
definitely not good. I'll look into this one today for sure.

**Comment by agross** [comment]
Can you please elaborate what it means for a feed to get treated as a floating feed? Will ripple check if there are newer versions when install/restore happens? (I think the answer is yes.)

In any case, even if there is no newer version available it should still be able to download/install the version requested by ripple.config, right? There is only one package version on nuget.org for System.Management.Automation.

Thanks!

**Comment by jmarnold** [comment]
The queries are different for floated feeds. We've only used it in smaller
scenarios but I'm sure we'd see problems with lots of nugets. I'm not 100%
that's what's happening but the query you saw in the log looked wrong to me.

Floated feeds/nugets are use when you always want the latest. I'll use this
nuget specifically for testing and let you know what I find.

**Comment by agross** [comment]
There's another, but possibly related issue with floated feeds: I tried installing a package "x" with a dependency on Rx-Core. The nuget.org feed was configured as floating. When executing `ripple install x --project blah` ripple just ignored Rx-Core without even printing a warning or error.

Until this is fixed, I think it's a safe(r) bet to configure the nuget.org feed as fixed only. What do you think?

**Comment by jmarnold** [comment]
I think that's a safe bet. I'm getting close to releasing 3.0 which will fix this.
