### ISSUE TITLE
Intermittent NRE when downloading nugets from TeamCity feeds

### ISSUE THREAD

**Issue by andreasohlund** [FubuMvcArchive/ripple#266]
We get a NRE now and then on ripple restore. This failing nuget is always one of the floats provided by the buildserver it selg.

I looked at the code but I couldn't see any obvious issues. Any pointers on how to debug this?

```
[23:12:36][RippleRestoreTarget] RippleRestoreTask.RestoreTask (7s)
[23:12:36][RippleRestoreTask.RestoreTask] Found 'ripple.config' in at 'Y:\BuildAgent\work\3e0c79eb07d58469\ripple.config'.
[23:12:36][RippleRestoreTask.RestoreTask] Restoring dependencies for solution NServiceBus.SqlServer to Y:\BuildAgent\work\3e0c79eb07d58469\src\packages
[23:12:43]
[RippleRestoreTask.RestoreTask] 
==========================================================================================
Missing Nugets: Could not find nugets
==========================================================================================
     ** Nugets
        * NServiceBus.AcceptanceTesting     Float
     ** Problems
        * NullReferenceException     Object reference not set to an instance of an object.
[23:12:43]
[RippleRestoreTask.RestoreTask] 
======================================
String: Could not restore dependencies
======================================

An unhandled exception occurred:
Exception:
Could not restore dependencies
[23:12:43]
[RippleRestoreTask.RestoreTask] 
=============================================
String: Error executing DownloadMissingNugets
=============================================

An unhandled exception occurred:
Exception:
Could not restore dependencies
StackTrace:
   at ripple.RippleAssert.Fail(String message, Object[] substitutions)
   at ripple.Steps.DownloadMissingNugets.Execute(RippleInput input, IRippleStepRunner runner)
   at ripple.RippleOperation.Execute(Boolean throwOnFailure)
Source:
ripple
TargetSite:
Void Fail(System.String, System.Object[])
[23:12:43]
[RippleRestoreTask.RestoreTask] 
========================
String: Error occurred: 
========================

An unhandled exception occurred:
Exception:
Could not restore dependencies
StackTrace:
   at ripple.RippleAssert.Fail(String message, Object[] substitutions)
   at ripple.Steps.DownloadMissingNugets.Execute(RippleInput input, IRippleStepRunner runner)
   at ripple.RippleOperation.Execute(Boolean throwOnFailure)
   at ripple.Commands.RestoreCommand.Execute(RestoreInput input)
   at ripple.RippleOperation.CommandExecutionExpression.Execute[TInput,TCommand](TInput input, TCommand command)
   at RippleRestoreTask.RestoreTask.InnerExecute(ILogListener logListener, String targetDirectory) in c:\dev\Particular\RippleRestoreTask\RippleRestoreTask\RippleRestoreTask.cs:line 68
   at RippleRestoreTask.RestoreTask.<>c__DisplayClass2.<Execute>b__0() in c:\dev\Particular\RippleRestoreTask\RippleRestoreTask\RippleRestoreTask.cs:line 35
   at Locker.ExecuteLocked(String name, Action action) in c:\dev\Particular\RippleRestoreTask\RippleRestoreTask\Locker.cs:line 20
   at RippleRestoreTask.RestoreTask.Execute() in c:\dev\Particular\RippleRestoreTask\RippleRestoreTask\RippleRestoreTask.cs:line 35
Source:
ripple
TargetSite:
Void Fail(System.String, System.Object[])

```

Full build log:

http://builds.particular.net/viewLog.html?buildId=34760&buildTypeId=NServiceBusSqlServer_1Build&tab=buildLog

**Comment by jmarnold** [comment]
@andreasohlund Are you able to reproduce that locally?

**Comment by jmarnold** [comment]
If so, I think I would start by modifying this guy:
https://github.com/DarthFubuMVC/ripple/blob/master/src/ripple/Nuget/NugetProblem.cs#L26

You could try shoving the stacktrace into the description that you get more info.

**Comment by andreasohlund** [comment]
I can't repro locally. I'll add the callstack and see what that gives
