### ISSUE TITLE
Initial build / package restore fails

### ISSUE THREAD

**Issue by jakejscott** [FubuMvcArchive/ripple#270]
So in the Tools > Options > NuGet Package Manager > Package Sources I had https://www.nuget.org/api/v2/ unchecked (as we have an internal NuGet feed). So it was failing to find packages.

Some context:
https://github.com/Particular/ServiceControl/issues/243

Here is the ripple.config

```
<?xml version="1.0"?>
<ripple xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Name>ServiceControl</Name>
  <NugetSpecFolder>packaging/nuget</NugetSpecFolder>
  <SourceFolder>src</SourceFolder>
  <BuildCommand>rake</BuildCommand>
  <FastBuildCommand>rake compile</FastBuildCommand>
  <DefaultFloatConstraint>Current</DefaultFloatConstraint>
  <DefaultFixedConstraint>Current,NextMajor</DefaultFixedConstraint>
  <Feeds>
    <Feed Url="https://builds.particular.net/guestAuth/app/nuget/v1/FeedService.svc" Mode="Float" Stability="Anything" />
    <Feed Url="http://nuget.org/api/v2" Mode="Fixed" Stability="ReleasedOnly" />
  </Feeds>
  <Nugets>
    <Dependency Name="Autofac" Version="3.1.1" Mode="Fixed" />
    <Dependency Name="Autofac.SignalR" Version="3.0.1" Mode="Fixed" />
    <Dependency Name="log4net" Version="2.0.0" Mode="Fixed" />
    <Dependency Name="Lucene.Net" Version="3.0.3" Mode="Fixed" />
    <Dependency Name="Microsoft.AspNet.SignalR.Client" Version="1.1.3" Mode="Fixed" />
    <Dependency Name="Microsoft.AspNet.SignalR.Core" Version="1.1.3" Mode="Fixed" />
    <Dependency Name="Microsoft.AspNet.SignalR.Owin" Version="1.1.3" Mode="Fixed" />
    <Dependency Name="Microsoft.Bcl" Version="1.1.3" Mode="Fixed" />
    <Dependency Name="Microsoft.Bcl.Build" Version="1.0.10" Mode="Fixed" />
    <Dependency Name="Microsoft.CompilerServices.AsyncTargetingPack" Version="1.0.1.0" Mode="Fixed" />
    <Dependency Name="Microsoft.CompilerServices.AsyncTargetingPack" Version="1.0.1" Mode="Fixed" />
    <Dependency Name="Microsoft.Data.Edm" Version="5.2.0.0" Mode="Fixed" />
    <Dependency Name="Microsoft.Data.OData" Version="5.2.0.0" Mode="Fixed" />
    <Dependency Name="Microsoft.Net.Http" Version="2.2.15" Mode="Fixed" />
    <Dependency Name="Microsoft.Owin" Version="2.0.0" Mode="Fixed" />
    <Dependency Name="Microsoft.Owin.Diagnostics" Version="2.0.0" Mode="Fixed" />
    <Dependency Name="Microsoft.Owin.Host.HttpListener" Version="2.0.0" Mode="Fixed" />
    <Dependency Name="Microsoft.Owin.Hosting" Version="2.0.0" Mode="Fixed" />
    <Dependency Name="Microsoft.WindowsAzure.ConfigurationManager" Version="1.8.0.0" Mode="Fixed" />
    <Dependency Name="Nancy" Version="0.20.0" Mode="Fixed" />
    <Dependency Name="Nancy.Bootstrappers.Autofac" Version="0.20.0" Mode="Fixed" />
    <Dependency Name="Nancy.Owin" Version="0.20.0" Mode="Fixed" />
    <Dependency Name="Newtonsoft.Json" Version="5.0.6" Mode="Fixed" />
    <Dependency Name="NLog" Version="2.0.1.2" Mode="Fixed" />
    <Dependency Name="NServiceBus" Version="4.4.0-Unstable0033" Mode="Float" />
    <Dependency Name="NServiceBus.AcceptanceTesting" Version="4.4.0-Unstable0033" Mode="Float" />
    <Dependency Name="NServiceBus.Autofac" Version="4.4.0-Unstable0033" Mode="Float" />
    <Dependency Name="NServiceBus.Host" Version="4.4.0-Unstable0033" Mode="Float" />
    <Dependency Name="NServiceBus.Interfaces" Version="4.4.0-Unstable0033" Mode="Float" />
    <Dependency Name="NServiceBus.RavenDB" Version="0.2.0-Unstable24" Mode="Float" />
    <Dependency Name="NUnit" Version="2.6.2" Mode="Fixed" />
    <Dependency Name="Owin" Version="1.0" Mode="Fixed" />
    <Dependency Name="Particular.CustomActions" Version="1.1.0" Mode="Float" />
    <Dependency Name="RavenDB.Client" Version="2.5.2838-Unstable" Mode="Fixed" Stability="Anything" />
    <Dependency Name="RavenDB.Database" Version="2.5.2838-Unstable" Mode="Fixed" Stability="Anything" />
    <Dependency Name="RavenDB.Embedded" Version="2.5.2838-Unstable" Mode="Fixed" Stability="Anything" />
    <Dependency Name="SharpZipLib" Version="0.86.0" Mode="Fixed" />
    <Dependency Name="System.Spatial" Version="5.2.0.0" Mode="Fixed" />
    <Dependency Name="WindowsAzure.Storage" Version="2.0.6.1" Mode="Fixed" />
  </Nugets>
  <Groups />
  <References>
    <IgnoreAssemblies />
  </References>
  <Nuspecs />
</ripple>
```

Here is the ripple.log file

```
20/02/2014 10:12:58 a.m.: [Info] Restoring dependencies for solution ServiceControl to c:\Projects\Particular\ServiceControl\src\packages
20/02/2014 10:12:58 a.m.: [Debug] 
==============================================================================================================
RippleOperation: ServiceControl (develop)
==============================================================================================================
     ** Ripple Steps
          1.) DownloadMissingNugets       Download missing nugets for ServiceControl                          
          2.) ExplodeDownloadedNugets     Explode nugets at c:\Projects\Particular\ServiceControl\src\packages
          3.) ProcessDirectives           Process directives from nugets                                      
          4.) FixReferences               Fix References                                                      

20/02/2014 10:13:10 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\log4net.2.0.0.0.nupkg
20/02/2014 10:13:11 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Lucene.Net.3.0.3.0.nupkg
20/02/2014 10:13:11 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.AspNet.SignalR.Client.1.1.3.0.nupkg
20/02/2014 10:13:12 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Autofac.SignalR.3.0.1.0.nupkg
20/02/2014 10:13:12 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Autofac.3.1.1.0.nupkg
20/02/2014 10:13:13 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.AspNet.SignalR.Owin.1.1.3.0.nupkg
20/02/2014 10:13:13 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.AspNet.SignalR.Core.1.1.3.0.nupkg
20/02/2014 10:13:14 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Bcl.1.1.3.0.nupkg
20/02/2014 10:13:14 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Bcl.Build.1.0.10.0.nupkg
20/02/2014 10:13:15 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.CompilerServices.AsyncTargetingPack.1.0.1.0.nupkg
20/02/2014 10:13:15 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Data.Edm.5.2.0.0.nupkg
20/02/2014 10:13:16 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Data.OData.5.2.0.0.nupkg
20/02/2014 10:13:17 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Net.Http.2.2.15.0.nupkg
20/02/2014 10:13:17 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Owin.2.0.0.0.nupkg
20/02/2014 10:13:18 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Owin.Diagnostics.2.0.0.0.nupkg
20/02/2014 10:13:18 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Owin.Host.HttpListener.2.0.0.0.nupkg
20/02/2014 10:13:19 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.Owin.Hosting.2.0.0.0.nupkg
20/02/2014 10:13:19 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Microsoft.WindowsAzure.ConfigurationManager.1.8.0.0.nupkg
20/02/2014 10:13:20 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Nancy.0.20.0.0.nupkg
20/02/2014 10:13:20 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Nancy.Bootstrappers.Autofac.0.20.0.0.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Nancy.Owin.0.20.0.0.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Newtonsoft.Json.5.0.6.0.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading Download and cache NLog.2.0.0.2000.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading Download and cache NServiceBus.4.5.0.0-Unstable0002.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading Download and cache NServiceBus.Interfaces.4.5.0.0-Unstable0002.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading Download and cache NServiceBus.AcceptanceTesting.4.5.0.0-Unstable0002.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\NUnit.2.6.2.0.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading Download and cache NServiceBus.Host.4.5.0.0-Unstable0002.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading Download and cache NServiceBus.RavenDB.0.3.0.0-Unstable0003.nupkg
20/02/2014 10:13:21 a.m.: [Debug] Downloading Download and cache NServiceBus.Autofac.4.5.0.0-Unstable0002.nupkg
20/02/2014 10:13:22 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Owin.1.0.0.0.nupkg
20/02/2014 10:13:22 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\Particular.CustomActions.1.2.1.0.nupkg
20/02/2014 10:13:26 a.m.: [Error] Could not find RavenDB.Client,2.5.2838-Unstable,Fixed
20/02/2014 10:13:26 a.m.: [Error] ripple.RippleFatalError: Could not find RavenDB.Client,2.5.2838-Unstable,Fixed
20/02/2014 10:13:31 a.m.: [Error] Could not find RavenDB.Database,2.5.2838-Unstable,Fixed
20/02/2014 10:13:31 a.m.: [Error] ripple.RippleFatalError: Could not find RavenDB.Database,2.5.2838-Unstable,Fixed
20/02/2014 10:13:35 a.m.: [Error] Could not find RavenDB.Embedded,2.5.2838-Unstable,Fixed
20/02/2014 10:13:35 a.m.: [Error] ripple.RippleFatalError: Could not find RavenDB.Embedded,2.5.2838-Unstable,Fixed
20/02/2014 10:13:36 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\SharpZipLib.0.86.0.0.nupkg
20/02/2014 10:13:36 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\System.Spatial.5.2.0.0.nupkg
20/02/2014 10:13:37 a.m.: [Debug] Downloading From filesystem: C:\Users\Jake.Scott\AppData\Roaming\ripple\WindowsAzure.Storage.2.0.6.1.nupkg
20/02/2014 10:17:19 a.m.: [Error] Error executing DownloadMissingNugets
20/02/2014 10:17:19 a.m.: [Error] System.AggregateException: One or more errors occurred. ---> ripple.RippleFatalError: Could not find RavenDB.Client,2.5.2838-Unstable,Fixed
   at ripple.Model.FeedService.nugetFor(Dependency dependency, Boolean retrying)
   at ripple.Model.FeedService.<.ctor>b__0(Dependency x)
   at FubuCore.Util.Cache`2.Fill(TKey key, Func`2 onMissing)
   at ripple.Model.FeedService.NugetFor(Dependency dependency)
   at ripple.Steps.DownloadMissingNugets.<>c__DisplayClass5.<restore>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ripple.Steps.DownloadMissingNugets.Execute(SolutionInput input, IRippleStepRunner runner)
   at ripple.RippleOperation.Execute(Boolean throwOnFailure)
---> (Inner Exception #0) ripple.RippleFatalError: Could not find RavenDB.Client,2.5.2838-Unstable,Fixed
   at ripple.Model.FeedService.nugetFor(Dependency dependency, Boolean retrying)
   at ripple.Model.FeedService.<.ctor>b__0(Dependency x)
   at FubuCore.Util.Cache`2.Fill(TKey key, Func`2 onMissing)
   at ripple.Model.FeedService.NugetFor(Dependency dependency)
   at ripple.Steps.DownloadMissingNugets.<>c__DisplayClass5.<restore>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #1) ripple.RippleFatalError: Could not find RavenDB.Database,2.5.2838-Unstable,Fixed
   at ripple.Model.FeedService.nugetFor(Dependency dependency, Boolean retrying)
   at ripple.Model.FeedService.<.ctor>b__0(Dependency x)
   at FubuCore.Util.Cache`2.Fill(TKey key, Func`2 onMissing)
   at ripple.Model.FeedService.NugetFor(Dependency dependency)
   at ripple.Steps.DownloadMissingNugets.<>c__DisplayClass5.<restore>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #2) ripple.RippleFatalError: Could not find RavenDB.Embedded,2.5.2838-Unstable,Fixed
   at ripple.Model.FeedService.nugetFor(Dependency dependency, Boolean retrying)
   at ripple.Model.FeedService.<.ctor>b__0(Dependency x)
   at FubuCore.Util.Cache`2.Fill(TKey key, Func`2 onMissing)
   at ripple.Model.FeedService.NugetFor(Dependency dependency)
   at ripple.Steps.DownloadMissingNugets.<>c__DisplayClass5.<restore>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

20/02/2014 10:17:19 a.m.: [Debug] 
=============================================================================================================================================================================================
Solution "ServiceControl": c:\Projects\Particular\ServiceControl\ripple.config
=============================================================================================================================================================================================
     ** Solution-Level
        * Autofac                                           3.1.1            
        * Autofac.SignalR                                   3.0.1            
        * log4net                                           2.0.0            
        * Lucene.Net                                        3.0.3            
        * Microsoft.AspNet.SignalR.Client                   1.1.3            
        * Microsoft.AspNet.SignalR.Core                     1.1.3            
        * Microsoft.AspNet.SignalR.Owin                     1.1.3            
        * Microsoft.Bcl                                     1.1.3            
        * Microsoft.Bcl.Build                               1.0.10           
        * Microsoft.CompilerServices.AsyncTargetingPack     1.0.1.0          
        * Microsoft.CompilerServices.AsyncTargetingPack     1.0.1            
        * Microsoft.Data.Edm                                5.2.0.0          
        * Microsoft.Data.OData                              5.2.0.0          
        * Microsoft.Net.Http                                2.2.15           
        * Microsoft.Owin                                    2.0.0            
        * Microsoft.Owin.Diagnostics                        2.0.0            
        * Microsoft.Owin.Host.HttpListener                  2.0.0            
        * Microsoft.Owin.Hosting                            2.0.0            
        * Microsoft.WindowsAzure.ConfigurationManager       1.8.0.0          
        * Nancy                                             0.20.0           
        * Nancy.Bootstrappers.Autofac                       0.20.0           
        * Nancy.Owin                                        0.20.0           
        * Newtonsoft.Json                                   5.0.6            
        * NLog                                              2.0.1.2          
        * NServiceBus                                       Float            
        * NServiceBus.AcceptanceTesting                     Float            
        * NServiceBus.Autofac                               Float            
        * NServiceBus.Host                                  Float            
        * NServiceBus.Interfaces                            Float            
        * NServiceBus.RavenDB                               Float            
        * NUnit                                             2.6.2            
        * Owin                                              1.0              
        * Particular.CustomActions                          Float            
        * RavenDB.Client                                    2.5.2838-Unstable
        * RavenDB.Database                                  2.5.2838-Unstable
        * RavenDB.Embedded                                  2.5.2838-Unstable
        * SharpZipLib                                       0.86.0           
        * System.Spatial                                    5.2.0.0          
        * WindowsAzure.Storage                              2.0.6.1          
     ** NuGet Feeds
        * Feed     https://builds.particular.net/guestAuth/app/nuget/v1/FeedService.svc (Float)
        * Feed     http://nuget.org/api/v2 (Fixed)                                             
     ** Projects
        * Project "Chocolatey"                                 c:\Projects\Particular\ServiceControl\src\Chocolatey\Chocolatey.csproj                                                        
             ** Dependencies
        * Project "ServiceControl"                             c:\Projects\Particular\ServiceControl\src\ServiceControl\ServiceControl.csproj                                                
             ** Dependencies
                * Autofac                                         Float
                * Autofac.SignalR                                 Float
                * Lucene.Net                                      Float
                * Microsoft.AspNet.SignalR.Core                   Float
                * Microsoft.AspNet.SignalR.Owin                   Float
                * Microsoft.Data.Edm                              Float
                * Microsoft.Data.OData                            Float
                * Microsoft.Owin                                  Float
                * Microsoft.Owin.Diagnostics                      Float
                * Microsoft.Owin.Host.HttpListener                Float
                * Microsoft.Owin.Hosting                          Float
                * Microsoft.WindowsAzure.ConfigurationManager     Float
                * Nancy                                           Float
                * Nancy.Bootstrappers.Autofac                     Float
                * Nancy.Owin                                      Float
                * Newtonsoft.Json                                 Float
                * NLog                                            Float
                * NServiceBus                                     Float
                * NServiceBus.Autofac                             Float
                * NServiceBus.Host                                Float
                * NServiceBus.Interfaces                          Float
                * NServiceBus.RavenDB                             Float
                * Owin                                            Float
                * RavenDB.Client                                  Float
                * RavenDB.Database                                Float
                * RavenDB.Embedded                                Float
                * SharpZipLib                                     Float
                * System.Spatial                                  Float
                * WindowsAzure.Storage                            Float
        * Project "ServiceControl.AcceptanceTests"             c:\Projects\Particular\ServiceControl\src\ServiceControl.AcceptanceTests\ServiceControl.AcceptanceTests.csproj                
             ** Dependencies
                * Microsoft.AspNet.SignalR.Client      Float
                * Microsoft.Bcl                        Float
                * Microsoft.Net.Http                   Float
                * Microsoft.Owin.Host.HttpListener     Float
                * Newtonsoft.Json                      Float
                * NLog                                 Float
                * NServiceBus                          Float
                * NServiceBus.Host                     Float
                * NServiceBus.Interfaces               Float
                * NUnit                                Float
        * Project "ServiceControl.Contracts"                   c:\Projects\Particular\ServiceControl\src\ServiceControl.Contracts\ServiceControl.Contracts.csproj                            
             ** Dependencies
                * NServiceBus.Interfaces     Float
        * Project "ServiceControl.IntegrationDemo"             c:\Projects\Particular\ServiceControl\src\ServiceControl.IntegrationDemo\ServiceControl.IntegrationDemo.csproj                
             ** Dependencies
        * Project "ServiceControl.Plugin.CustomChecks"         c:\Projects\Particular\ServiceControl\src\ServiceControl.Plugin.CustomChecks\ServiceControl.Plugin.CustomChecks.csproj        
             ** Dependencies
                * NServiceBus                Float
                * NServiceBus.Interfaces     Float
        * Project "ServiceControl.Plugin.DebugSession"         c:\Projects\Particular\ServiceControl\src\ServiceControl.Plugin.DebugSession\ServiceControl.Plugin.DebugSession.csproj        
             ** Dependencies
        * Project "ServiceControl.Plugin.Heartbeat"            c:\Projects\Particular\ServiceControl\src\ServiceControl.Plugin.Heartbeat\ServiceControl.Plugin.Heartbeat.csproj              
             ** Dependencies
                * NServiceBus                Float
                * NServiceBus.Interfaces     Float
        * Project "ServiceControl.Plugin.SagaAudit"            c:\Projects\Particular\ServiceControl\src\ServiceControl.Plugin.SagaAudit\ServiceControl.Plugin.SagaAudit.csproj              
             ** Dependencies
                * NServiceBus                Float
                * NServiceBus.Interfaces     Float
        * Project "ServiceControl.Plugin.SagaAudit.Sample"     c:\Projects\Particular\ServiceControl\src\ServiceControl.Plugin.SagaAudit.Sample\ServiceControl.Plugin.SagaAudit.Sample.csproj
             ** Dependencies
        * Project "ServiceControl.UnitTests"                   c:\Projects\Particular\ServiceControl\src\ServiceControl.UnitTests\ServiceControl.UnitTests.csproj                            
             ** Dependencies
                * NServiceBus                Float
                * NServiceBus.Interfaces     Float
                * NUnit                      Float
     ** Missing
        * Autofac                                           3.1.1            
        * Autofac.SignalR                                   3.0.1            
        * log4net                                           2.0.0            
        * Lucene.Net                                        3.0.3            
        * Microsoft.AspNet.SignalR.Client                   1.1.3            
        * Microsoft.AspNet.SignalR.Core                     1.1.3            
        * Microsoft.AspNet.SignalR.Owin                     1.1.3            
        * Microsoft.Bcl                                     1.1.3            
        * Microsoft.Bcl.Build                               1.0.10           
        * Microsoft.CompilerServices.AsyncTargetingPack     1.0.1.0          
        * Microsoft.Data.Edm                                5.2.0.0          
        * Microsoft.Data.OData                              5.2.0.0          
        * Microsoft.Net.Http                                2.2.15           
        * Microsoft.Owin                                    2.0.0            
        * Microsoft.Owin.Diagnostics                        2.0.0            
        * Microsoft.Owin.Host.HttpListener                  2.0.0            
        * Microsoft.Owin.Hosting                            2.0.0            
        * Microsoft.WindowsAzure.ConfigurationManager       1.8.0.0          
        * Nancy                                             0.20.0           
        * Nancy.Bootstrappers.Autofac                       0.20.0           
        * Nancy.Owin                                        0.20.0           
        * Newtonsoft.Json                                   5.0.6            
        * NLog                                              2.0.1.2          
        * NServiceBus                                       Float            
        * NServiceBus.AcceptanceTesting                     Float            
        * NServiceBus.Autofac                               Float            
        * NServiceBus.Host                                  Float            
        * NServiceBus.Interfaces                            Float            
        * NServiceBus.RavenDB                               Float            
        * NUnit                                             2.6.2            
        * Owin                                              1.0              
        * Particular.CustomActions                          Float            
        * RavenDB.Client                                    2.5.2838-Unstable
        * RavenDB.Database                                  2.5.2838-Unstable
        * RavenDB.Embedded                                  2.5.2838-Unstable
        * SharpZipLib                                       0.86.0           
        * System.Spatial                                    5.2.0.0          
        * WindowsAzure.Storage                              2.0.6.1          

```

**Comment by JustinThirkell** [comment]
you haven't added your internal feed to ripple.config

in your case you're going to want something like this:

``` xml
<ripple xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Feeds>
    <Feed Url="http://build.fubu-project.org/guestAuth/app/nuget/v1/FeedService.svc" Mode="Float" Stability="ReleasedOnly" />
    <Feed Url="http://nuget.org/api/v2" Mode="Fixed" Stability="ReleasedOnly" />
    <Feed Url="http://nuget.wherever.your.internal.feed.is/api/v2/" Mode="Fixed" Stability="Anything" />
  </Feeds>
```

i've noticed even if you remove the default feed urls ripple seems to keep re-adding them back in.

**Comment by jmarnold** [comment]
@Justin,

I'm going to look into the urls being added back in. Can you open an issue
for me on that one?

Thanks!
