### ISSUE TITLE
fubu upgrade errors out with directory locking problems

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#44]
Does this every single time, even if you close the solution:

Error executing ExplodeDownloadedNugets
# 
# 

IOException: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive)
   at FubuCore.FileSystem.CleanDirectory(String directory)
   at ripple.Nuget.NugetFile.ExplodeTo(String directory) in c:\code\ripple\src\ripple\Nuget\NugetFile.cs:line 102
   at ripple.Steps.ExplodeDownloadedNugets.<Execute>b__0(INugetFile nuget) in c:\code\ripple\src\ripple\Steps\ExplodeDownloadedNugets.cs:line 20
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at ripple.Steps.ExplodeDownloadedNugets.Execute(SolutionInput input, IRippleStepRunner runner) in c:\code\ripple\src\ripple\Steps\ExplodeDownloadedNugets.cs:line 16
#    at ripple.RippleOperation.Execute(Boolean throwOnFailure) in c:\code\ripple\src\ripple\RippleOperation.cs:line 60
# 

Maybe we're doing something wrong timing wise.  Either way, it leaves the solution directory in an invalid state.  Usually takes a ripple restore afterward to make it usable again.

**Comment by jmarnold** [comment]
Got it 043dd68866b9e3209f5af11a4c2ce4c455e79509
