### ISSUE TITLE
Nuspecs without XML namespaces throw un-actionable error

### ISSUE THREAD

**Issue by KevM** [FubuMvcArchive/ripple#91]
I had some old nuspecs without XML namespaces: 

``` xml
<package >
  <metadata>
    <id>Dovetail.SDK.Fubu</id>
    <version>0.0.0</version>
    <title>Dovetail Bootstrap + FubuMVC</title>
     <!-- yadda yadda -->
  </metadata>
</package>
```

And received this error for `ripple create-packages`

```
5/24/2013 9:59:56 AM: [Error] Error executing CreatePackages
5/24/2013 9:59:56 AM: [Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at ripple.Local.NuspecDocument.get_Name() in c:\projects\ripple\src\ripple\Local\NuspecDocument.cs:line 112
   at ripple.Local.NugetSpec.ReadFrom(String filename) in c:\projects\ripple\src\ripple\Local\NugetSpec.cs:line 56
   at ripple.Model.PublishingService.<>c__DisplayClass5.<SpecificationsFor>b__4(String file) in c:\projects\ripple\src\ripple\Model\IPublishingService.cs:line 50
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\EnumerableExtensions.cs:line 78
   at ripple.Model.SolutionFiles.ForNuspecs(Solution solution, Action`1 action) in c:\projects\ripple\src\ripple\Model\ISolutionFiles.cs:line 81
   at ripple.Model.PublishingService.SpecificationsFor(Solution solution) in c:\projects\ripple\src\ripple\Model\IPublishingService.cs:line 48
   at ripple.Model.Solution.findSpecifications() in c:\projects\ripple\src\ripple\Model\Solution.cs:line 223
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at ripple.Model.Solution.get_Specifications() in c:\projects\ripple\src\ripple\Model\Solution.cs:line 161
   at ripple.Steps.CreatePackages.execute(CreatePackagesInput input, IRippleStepRunner runner) in c:\projects\ripple\src\ripple\Steps\CreatePackages.cs:line 16
   at ripple.Steps.RippleStep`1.Execute(SolutionInput input, IRippleStepRunner runner) in c:\projects\ripple\src\ripple\Steps\RippleStep.cs:line 13
   at ripple.RippleOperation.Execute(Boolean throwOnFailure) in c:\projects\ripple\src\ripple\RippleOperation.cs:line 79
```

I had to crack into the source to figure this out. Adding the namespaces fixed things: 

``` xml
<?xml version="1.0"?>
<package xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <metadata xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
```

**Comment by jmarnold** [comment]
I think it'll be much easier to spit out a contextual error saying what to
do than support both. The XML namespacing crap was a pain.

**Comment by KevM** [comment]
Yes when name spacing is in effect you have to check all of your xpath selects for a null result. Sounds like the XMLSchema in this case is very forgiving (lots of optionals) or you are not doing validation.
